name: Node.js build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'kieler/elkjs'
          path: 'elkjs'
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - working-directory: elkjs
        run: npm i
      
