name: Node.js build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          repository: 'kieler/elkjs'
          path: 'elkjs'
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: |
          chmod +x elkjs/gradlew
          
      - working-directory: elkjs
        run: |
          npm install
          npm run build --if-present
          npm test
