name: Node.js build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4
        with:
          repository: 'kieler/elkjs'
          path: elkjs
          
      - uses: actions/checkout@v4
        with:
          repository: 'eclipse/elk'
          ref: master
          path: elk
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: |
          chmod +x elkjs/gradlew
          
      - working-directory: elkjs
        run: |
          npm install
          npm run build --if-present
          npm test

      - working-directory: elkjs
        run: |
          ls -R

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'lib'
          filename: "elkjs-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "lib/elkjs-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
